#!/bin/bash

REGION="United_States"

reconnect() {
	timeout 10s nordvpn disconnect
	timeout 10s nordvpn connect $REGION
}

services() {
	sudo pkill -f nordvpn
	sudo pkill -f nordvpnd
	sudo systemctl restart nordvpn.service
	sudo systemctl restart nordvpnd.service
}

sudo iptables --flush
services
sleep 10
reconnect
