#!/usr/bin/python3

import time
import sys

def wiggler(wigglee, wiggle_frequency):
    while True:
        for i in range(0, 20):
            print(i * " " + wigglee)
            time.sleep(wiggle_frequency)
        for i in range(20, 0, -1):
            print(i * " " + wigglee)
            time.sleep(wiggle_frequency)

if __name__ == "__main__":
    args = sys.argv[1:]
    char = "🐍"
    freq = 0.0001

    if len(args) >= 1:
        char = args[0]
    if len(args) >= 2:
        freq = args[1]

    wiggler(char * 5, float(freq))
